SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio AS precio_EUR, ROUND((precio * 1.13), 2) AS precio_USD FROM producto;
SELECT nombre AS 'nom de producto', precio AS euros, ROUND((precio * 1.13), 2) AS dolars FROM producto;
SELECT UPPER(nombre), precio FROM producto;
SELECT LOWER(nombre), precio FROM producto;
SELECT nombre, UPPER(SUBSTRING(nombre, 1, 2)) AS abbr FROM fabricante;
SELECT nombre, ROUND(precio) FROM producto;
SELECT nombre, FLOOR(precio) FROM producto;
SELECT f.codigo FROM fabricante f, producto p WHERE f.codigo = p.codigo_fabricante;
SELECT DISTINCT f.codigo FROM fabricante f, producto p WHERE f.codigo = p.codigo_fabricante;
SELECT nombre FROM fabricante ORDER BY nombre;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre FROM producto ORDER BY nombre, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 2 OFFSET 3;
SELECT nombre, precio FROM producto ORDER BY precio LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2;
SELECT p.nombre AS producto, precio, f.nombre AS fabricante FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo;
SELECT p.nombre AS producto, precio, f.nombre AS fabricante FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo ORDER BY fabricante;
SELECT p.codigo AS codigo_producto, p.nombre AS producto, f.codigo AS codigo_fabricante, f.nombre AS fabricante FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo;
SELECT p.nombre AS producto, precio, f.nombre AS fabricante FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo ORDER BY precio LIMIT 1;
SELECT p.nombre AS producto, precio, f.nombre AS fabricante FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo ORDER BY precio DESC LIMIT 1;
SELECT p.codigo, p.nombre FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre = 'Lenovo';
SELECT p.codigo, p.nombre FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre = 'Crucial' AND precio > 200;
SELECT p.codigo, p.nombre AS producto, f.nombre AS fabricante FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND (f.nombre = 'Asus' OR f.nombre = 'Hewlett-Packard' OR f.nombre = 'Seagate');
SELECT p.codigo, p.nombre AS producto, f.nombre AS fabricante FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre IN ('Asus', 'Hewlett-Packard', 'Seagate');
SELECT p.nombre, precio FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND RIGHT(f.nombre, 1) = 'e';
SELECT p.nombre, precio FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND LOCATE('w', f.nombre) > 0;
SELECT p.codigo, p.nombre AS producto, f.nombre AS fabricante FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND precio >= 180 ORDER BY precio DESC, p.nombre;
SELECT DISTINCT f.codigo, f.nombre FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo;
SELECT DISTINCT f.nombre AS fabricante, p.nombre AS producto FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT * FROM fabricante WHERE codigo NOT IN ( SELECT codigo_fabricante FROM producto );
SELECT codigo, nombre FROM producto WHERE codigo_fabricante IN ( SELECT codigo FROM fabricante WHERE nombre = 'Lenovo' );
SELECT * FROM producto WHERE precio = ( SELECT precio FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre = 'Lenovo' ORDER BY precio DESC LIMIT 1 );
SELECT p.nombre FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre = 'Lenovo' ORDER BY precio DESC LIMIT 1;
SELECT p.nombre FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre = 'Hewlett-Packard' ORDER BY precio LIMIT 1;
SELECT * FROM producto WHERE precio >= ( SELECT precio FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre = 'Lenovo' ORDER BY precio DESC LIMIT 1 );
SELECT p.codigo, p.nombre, precio FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre = 'Asus' AND precio > ( SELECT AVG(p.precio) FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre = 'Asus' );